### PR TITLE
.github/workflows: Use new setup-go go-version-file input

### PR DESCRIPTION
**Pull request by bflad**
Reference: https://github.com/actions/setup-go/releases/tag/v3.1.0

### CODE REVIEW

**Comment by bflad** [comment]
Hmm. Going to debug `actionlint` to see if there's hardcoded information inside it and raise an issue if necessary. https://github.com/actions/setup-go/blob/v3/action.yml has the new input correctly.

**Comment by bflad** [comment]
Issue: https://github.com/rhysd/actionlint/issues/139
Potential fix: https://github.com/rhysd/actionlint/pull/140

**Comment by radeksimko** [comment]
FYI the new setting should also support reading `.go-version` - unsure if you intend to test against latest compatible version or the same version that you likely end up developing with locally (assuming you have `goenv` installed).

**Comment by bflad** [comment]
@radeksimko thanks for the nudge here -- I was actually looking to also remove `.go-version` files as part of this. I think the terraform-plugin-* projects are fine with CI/releases using the latest patch version as defined by the `go.mod`. I don't think anyone on the maintainers team uses `goenv`, but maybe that's a feature request that needs to be submitted to that project if it is not already supported functionality.

**Comment by detro** [comment]
`.goenv` user here :)

**Comment by bflad** [comment]
Good to know, @detro! If you'd like to keep the `goenv` specific handling around, please reach out. It's always been a pain to keep the `.go-version` up to date since as far as I know, there's not a way to handle it via dependabot.

actionlint is now happy with the new actions/setup-go `go-version-file` input and according to the last two commits, it seems to work as expected with either `go.mod` or `.go-version`.

**Review by bendbennett — APPROVED** [review]

**Review by detro — APPROVED** [review]
Forgot to apply a 👍 to this, sorry

**Pull request merged**
